# functions/cloudbuild.yaml
steps:
  # 1) Install deps (cached layer)
  - id: 'npm-ci'
    name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['ci', '--ignore-scripts']

  # 2) TypeScript compile
  - id: 'tsc'
    name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['run', 'build']
    env: ['NODE_ENV=production']

  # 3) Deploy only changed Functions (beta)  
  - id: 'deploy-fns'
    name: 'gcr.io/cloud-builders/gcloud'
    dir: 'functions'
    entrypoint: gcloud
    args:
      [
        'functions', 'deploy', 'createReport', 'listMyReports',
        '--region=asia-southeast1',
        '--runtime=nodejs20',
        '--source=.',
        '--entry-point=index',
        '--trigger-call',
        '--allow-unauthenticated'   # remove if you want only authed calls
      ]
    # For multiple functions you can deploy "*" in one step if using v2.

timeout: 900s
