steps:
  # 1) compile TypeScript
  - id: tsc
    name: gcr.io/cloud-builders/npm
    dir: functions
    args: ['run', 'build']

  # 2) deploy createReport
  - id: deploy-create
    name: gcr.io/cloud-builders/gcloud
    dir: functions
    args:
      [
        'functions', 'deploy', 'createReport',
        '--region=asia-southeast1',
        '--runtime=nodejs20',
        '--source=.',
        '--entry-point', 'createReport',
        '--trigger-http',
        '--allow-unauthenticated'
      ]

  # 3) deploy listMyReports
  - id: deploy-list
    name: gcr.io/cloud-builders/gcloud
    dir: functions
    args:
      [
        'functions', 'deploy', 'listMyReports',
        '--region=asia-southeast1',
        '--runtime=nodejs20',
        '--source=.',
        '--entry-point', 'listMyReports',
        '--trigger-http',
        '--allow-unauthenticated'
      ]