# .github/workflows/deploy-functions.yml
name: Backend Integration

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'release/**'
      - 'test/**'
      - 'docs/**'
      - 'ci/**'
    paths:
      - 'functions/**'
      - '.github/workflows/deploy-functions.yml'
      - 'firebase.json'
      - '.firebaserc'

permissions:
  id-token: write    # needed to mint the OIDC token
  contents: read

jobs:
  lint:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Functions dependencies
        run: npm ci --prefix functions

      - name: Lint Functions
        run: |
          cd functions
          npm run lint
        env:
          CI: true

  test:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Functions dependencies
        run: npm ci --prefix functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Run Tests
        run: |
          cd functions
          npm run serveAndTest
        env:
          CI: true

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            functions/logs
            functions/test-results

      - name: Test Report
        id: test-reports
        uses: dorny/test-reporter@v2
        if: always()    # run this step even if previous step failed
        with:
          name: JEST Tests
          path: functions/test-results/*.xml    
          reporter: jest-junit
          fail-on-error: false

      # - name: Test Badge
      #   uses: schneegans/dynamic-badges-action@v1.6.0
      #   with:
      #     auth: ${{ secrets.GIST_SECRET }}
      #     gistID: a467edbe2a1e888a4e18ff8c1097b5ec
      #     label: tests
      #     message: ${{ steps.test-reports.outputs.summary }}
      #     color: ${{ steps.test-reports.outputs.color }}

  deploy:
    name: Deploy Backend to Firebase Functions
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()  # Only deploy on main branch

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/334635767532/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'cloud-function-backend@th-stray.iam.gserviceaccount.com'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Functions dependencies
        run: npm ci --prefix functions

      - name: Build and Deploy Functions
        run: npm run deploy --prefix functions
